doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\src\Infrastructure\Database\Migrations
        # as Migrations classes should NOT be autoloaded
        'App\src\Infrastructure\Database\Migrations': '%kernel.project_dir%/src/Infrastructure/Database/Migrations'
    enable_profiler: false
