controllers:
    resource:
        path: ../src/Infrastructure/Controllers/
        namespace: App\Infrastructure\Controllers
    type: attribute

api_login_check:
    path: /api/login_check

send_email:
    path: /send-email
    controller: App\Infrastructure\Controllers\SendEmailController::sendEmail

update_currency_rate:
    path: /update-currency-rate
    controller: App\Infrastructure\Controllers\UpdateCurrencyController::updateCurrencyRate
    methods: [GET]
#not_found:
#    path: /{catchall}
#    controller: App\Infrastructure\Controllers\NotFoundController::notFound